steps:
- name: 'openjdk:11'
  entrypoint: 'javac'
  args: ['./src/additonner.java']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './dist/additonner.jar', 'gs://appjava/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://appjava/additonner.jar', '/home/molkaghammam2/java_apps']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '/home/molkaghammam2/java_apps/java_project.service', 'gs://appjava/']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args:
    - 'compute'
    - 'ssh'
    - 'useradm@instance-20240227-124824'
    - '--zone=us-central1-a'
    - '--command'
    - |
      sudo cp /home/molkaghammam2/java_apps/java_project.service /etc/systemd/system/
      sudo systemctl daemon-reload
      sudo systemctl enable java_project.service
      sudo systemctl start java_project.service
      java -jar /home/molkaghammam2/java_apps/additonner.jar
    - '--quiet'
