steps:
- name: 'maven:3.8.4'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'mvn compile'

- name: 'maven:3.8.4'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'mvn package'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'app'
  - 'deploy'
 dir: '.'
