steps:
- name: 'openjdk:11'
  entrypoint: 'javac'
  args: ['./src/additonner.java']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './dist/additonner.jar', 'gs://appjava/']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'scp', './dist/additonner.jar', 'instance-20240227-124824:~/']
