steps:
- name: 'maven:3.6.3-jdk-11'
  args: ['mvn', 'clean', 'install']

artifacts:
  objects:
    location: 'gs://appjava'
  # optional: specify files to be uploaded as artifacts
  files:
  - 'target/additon.jar'
