steps:
  # Étape pour installer les dépendances et construire l'application
  - name: 'maven:3.6.3-jdk-11'
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']

# Spécifiez toute substitution que vous souhaitez utiliser
# substitutions:
#   _VOS_SUBSTITUTIONS: vos-valeurs
