steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/ghammammolka/java_project.git']

- name: 'gcr.io/cloud-builders/ant'
  args: ['-f', 'build.xml', 'build']

images:
- 'gcr.io/cloud-builders/ant'

# Spécifiez le chemin d'accès à votre code source
