steps:
- name: 'openjdk:11'
  entrypoint: 'javac'
  args: ['./src/additonner.java']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './dist/additonner.jar', 'gs://appjava/']
  
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://appjava/additonner.jar', '/home/molkaghammam2']

- name: 'openjdk:11'
  entrypoint: 'java'
  args: ['-jar', '/home/molkaghammam2/additonner.jar']
