steps:
- name: 'openjdk:11'
  entrypoint: 'javac'
  args: ['./src/additonner.java']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './dist/additonner.jar', 'gs://appjava/']
  
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://appjava/additonner.jar', '/home/molkaghammam2/jars/addition.jar']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'scp', '/home/molkaghammam2/jars/addition.jar', 'molkaghammam2@instance-20240227-124824:/home/molkaghammam2/']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'molkaghammam2@instance-20240227-124824', '--command', 'java -jar /home/molkaghammam2/jars/addition.jar']
