# Configuration de l'application Java
java:
  source_dir: src            # Répertoire contenant les fichiers source Java
  output_dir: build/classes  # Répertoire de sortie pour les fichiers compilés
  main_class: additonner  # Classe principale de votre application
  dependencies:
    - group: org.example
      artifact: dependency1
      version: 1.0.0
    - group: org.example
      artifact: dependency2
      version: 2.0.0

# Configuration du fichier JAR
jar:
  output_file: dist/additonner.jar  # Chemin et nom du fichier JAR de sortie
  include_files:
    - src/main/resources/cloudbuild.yaml  # Fichier YAML à inclure dans le JAR
