steps:
- name: 'openjdk:11'
  entrypoint: 'javac'
  args: ['./src/additonner.java']

- name: 'openjdk:11'
  entrypoint: 'jar'
  args: ['cf', '/home/molkaghammam2/jars/addition.jar', '-C', './classes/', 'additonner.class']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '/home/molkaghammam2/jars/addition.jar', 'gs://appjava/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://appjava/additonner.jar', '/home/molkaghammam2/jars/addition.jar']

- name: 'openjdk:11'
  entrypoint: 'java'
  args: ['-jar', '/home/molkaghammam2/jars/addition.jar']
