steps:
- name: 'openjdk:11'
  entrypoint: 'javac'
  args: ['./src/additonner.java']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './dist/additonner.jar', 'gs://appjava/']
  
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://appjava/additonner.jar', '/home/molkaghammam2']

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-d', '-p', '8080:8080', '-v', '/home/molkaghammam2/additonner.jar:/app/additonner.jar', 'openjdk:11', 'java', '-jar', '/app/additonner.jar']
