steps:
  # Étape pour installer Apache Ant
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update -y
        apt-get install -y ant

  # Étape pour construire le projet avec Apache Ant
  - name: 'gcr.io/cloud-builders/ant'
    args: ['build']

  # Nouvelle étape pour construire l'application Java
  - name: 'gcr.io/cloud-builders/ant'
    args: ['build-java']

# Spécifiez toute substitution que vous souhaitez utiliser
# substitutions:
#   _VOS_SUBSTITUTIONS: vos-valeurs
