steps:
- name: 'openjdk:11'
  entrypoint: 'javac'
  args: ['./src/additonner.java']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './dist/additonner.jar', 'gs://appjava/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://appjava/additonner.jar', '/home/molkaghammam2']
  
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args:
    - 'compute'
    - 'ssh'
    - 'molkaghammam2@instance-20240227-124824'
    - '--zone=us-central1-a'
    - '--command'
    - 'java -jar /home/molkaghammam2/additonner.jar 5 30'    
